config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :recipes
  get 'tasks/index'

  get 'tasks/new'

  namespace :api, defaults: {format: :json} do
    post 'authenticate', to: 'authentication#authenticate'
    get 'test', to: 'test#index'
  end

  resources :evolutions, except: [:show]
  resources :stanhome_products, except: [:show]
  resources :tasks
  resources :recipes

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get 'home/activate_api'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html {redirect_to @recipe, notice: 'Recette crée avec succès'}
        format.json {render :show, status: :created, location: @recipe}
      else
        format.html {render :new}
        format.json {render json: @recipe.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /recipes/1
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html {redirect_to @recipe, notice: 'Recette mis à jour avec succès'}
        format.json {render :show, status: :ok, location: @recipe}
      else
        format.html {render :edit}
        format.json {render json: @recipe.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html {redirect_to recipes_url, success: 'Recette supprimée avec succès'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:nb_persons, :preparation_time, :cooking_time, :ingredients, :category_id, :preparation, :name)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <% if recipe.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <ul>
            <% recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group row">
      <%= f.label :name, 'Nom', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_field :name, autofocus: true, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :nb_persons, 'Nombre de personnes', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.number_field :nb_persons, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :preparation_time, 'Temps de préparation', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.number_field :preparation_time, class: 'form-control', required: true %>
        <small class="form-text text-muted">
          Minutes
        </small>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :cooking_time, 'Temps de cuisson / repos', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.number_field :cooking_time, class: 'form-control', required: true %>
        <small class="form-text text-muted">
          Minutes
        </small>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :ingredients, 'Ingrédients', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_area :ingredients, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :category, 'Catégorie', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :category_id, Category.pluck(:name, :id), {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :preparation, 'Etapes de Préparation', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_area :preparation, class: ' tinymce', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit 'Enregistrer', class: 'btn btn-outline-success' %>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<% content_for :tab, :recipe %>
<% content_for :content do %>
    <div class="card">
      <div class="card-header text-white bg-secondary">
        <h3>Modification d'une recette</h3>
      </div>
      <div class="card-body">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
<% end %>
<%= render template: 'layouts/profile' %>

app/views/recipes/index.html.erb
<% content_for :tab, :recipe %>
<% content_for :content do %>
    <div class="card">
      <div class="card-header text-white bg-secondary">
        <h3>Recettes</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover table-inverse">
          <thead>
          <tr>
            <th>Nom</th>
            <th class="text-center">Catégorie</th>
            <th class="text-center"></th>
          </tr>
          </thead>
          <tbody>
          <% @recipes.each do |recipe| %>
              <tr>
                <th scope="row"><%= recipe.name %></th>
                <td><%= recipe.category.name %></td>
                <td>
                  <%= link_to 'Voir', recipe, class: 'btn btn-sm btn-info' %>
                  <%= link_to 'Editer', edit_recipe_path(recipe), class: 'btn btn-sm btn-success' %>
                  <%= link_to 'Supprimer', recipe, method: :delete, data: {confirm: 'Etes-vous sur ?'}, class: 'btn btn-sm btn-danger' %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= link_to 'Ajouter une Recette', new_recipe_path, class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>
<%= render template: 'layouts/profile' %>

app/views/recipes/new.html.erb
<% content_for :tab, :recipe %>
<% content_for :content do %>
    <div class="card">
      <div class="card-header text-white bg-secondary">
        <h3>Ajout d'une recette</h3>
      </div>
      <div class="card-body">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
<% end %>
<%= render template: 'layouts/profile' %>

app/views/recipes/show.html.erb
<% content_for :tab, :recipe %>
<% content_for :content do %>
    <div class="card">
      <div class="card-header text-white bg-secondary">
        <h3><%= @recipe.name.capitalize %></h3>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-4 text-right">Temps de préparation :</div>
          <div class="col-sm-2 text-left">
            <span class="badge badge-primary"><%= @recipe.preparation_time %> min.</span>
          </div>
          <div class="col-sm-4 text-right">Temps de cuisson / repos :</div>
          <div class="col-sm-2 text-left">
            <span class="badge badge-primary"><%= @recipe.cooking_time %> min.</span>
          </div>
          <div class="col-sm-4 text-right">Personnes :</div>
          <div class="col-sm-2 text-left">
            <span class="badge badge-primary"><%= @recipe.nb_persons %></span>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header text-white bg-secondary">
        <h5>Etapes de préparation</h5>
      </div>
      <div class="card-body">
        <%= @recipe.preparation.html_safe %>
      </div>
    </div>
<% end %>
<%= render template: 'layouts/profile' %>