config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :recipes
  get 'tasks/index'

  get 'tasks/new'

  namespace :api, defaults: {format: :json} do
    post 'authenticate', to: 'authentication#authenticate'
    get 'test', to: 'test#index'
  end

  resources :evolutions, except: [:show]
  resources :stanhome_products, except: [:show]
  resources :tasks
  resources :recipes

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'
  get 'home/activate_api'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud

    if user.admin?
      can :manage, :all
    else
      can :crud, Evolution, {user_id: user.id}
      can :crud, StanhomeProduct
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/evolution.rb
class Evolution < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

  include ImageUploader::Attachment.new(:image)

  validates :name, presence: true
  validates :content, presence: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
end

app/models/stanhome_product.rb
class StanhomeProduct < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable
  devise :omniauthable, omniauth_providers: [:facebook]

  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  attr_accessor :login
  attr_reader :password_digest

  has_many :posts
  has_many :evolutions

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end

  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.username = auth.info.name
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end
end

app/models/user_api.rb
class UserApi < ApplicationRecord
  self.table_name = 'users'

  has_secure_password

  has_many :posts
  has_many :evolutions
  validates_presence_of :email, :password

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  before_action :authenticate_request
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    render json: {error: 'Not Authorized'}, status: 401 unless @current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  require 'rest-client'

  def index
    redirect_to new_user_session_path unless user_signed_in?

    @api_password = current_user.api_password
  end

  def activate_api
    user_api = UserApi.find(current_user.id)
    password_generated = SecureRandom.hex(18)
    user_api.password = password_generated
    user_api.api_password = password_generated
    user_api.save
    redirect_to :root, success: 'Mot de passe API généré avec succès !'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, :image)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @incomplete_tasks = Task.where(complete: false)
    @complete_tasks = Task.where(complete: true)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(allowed_params)

    respond_to do |f|
      f.html {redirect_to tasks_url}
      f.js
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(allowed_params)

    respond_to do |f|
      f.html {redirect_to tasks_url}
      f.js
    end
  end

  def destroy
    @task = Task.destroy(params[:id])

    respond_to do |f|
      f.html {redirect_to tasks_url}
      f.js
    end
  end

  private

  def allowed_params
    params.require(:task).permit(:name, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def jwt_token
    payload = {
        :user_id => current_user.id,
        :user_name => current_user.username,
        :exp => Time.now.to_i + 60
    }
    JWT.encode payload, '4fvs6d51fv815s1bsg651fdv81fb65fs1gnd1dq62d1vs8b1e951tui9n1bv5dcs9c15qsc1vg65hd1u9kuiy156g1fev'
  end

  def remote_ip
    r = RestClient.get'http://ip-api.com/json'
    JSON.parse(r)['query']
  end

  def get_ip_info
    r = RestClient.get'http://ip-api.com/json/' + remote_ip
    JSON.parse(r)
  end
end

app/helpers/evolutions_helper.rb
module EvolutionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="IntraHome Portal">
  <meta name="author" content="NuBOX DevCom">
  <%= csrf_meta_tags %>
  <link rel="icon" href="<%= image_url('favicon.ico') %>">
  <title>IntraHome Portal</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag 'logo.png', {width: '30px'} %>
    IntraHome
  </a>
  <ul class="navbar-nav mr-auto"></ul>
  <% if user_signed_in? %>
      <span class="navbar-text">Bienvenue <strong><%= current_user.username %></strong> !</span>
  <% end %>
</nav>
<div class="container-fluid" style="padding: 5rem 1.5rem; text-align: center;">
  <% flash.each do |name, msg| %>
      <% case name
           when 'notice'
             name = 'info'
           when 'alert'
             name = 'warning'
         end
      %>
      <div class="alert alert-<%= name %>" role="alert"><%= msg %></div>
  <% end %>
  <%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-eval': false, 'data-turbolinks-track': 'reload' %>
<%= tinymce %>
</body>
</html>

app/views/layouts/profile.html.erb
<div class="row">
  <div class="col-md-9">
    <%= yield(:content) %>
  </div>
  <div class="col-md-3">
    <div class="list-group">
      <a href="<%= root_path %>" class="list-group-item<%= yield(:tab) == 'home' ? ' active' : '' %> list-group-item-secondary">Accueil</a>
    </div>
    <h2 class="mt-4">Utilisateurs En Ligne</h2>
    <div class="list-group">
      <div class="list-group-item">
        <ul id="presence" data-token="<%= jwt_token %>" class="text-left text-muted" data-user="<%= current_user.username %>"></ul>
      </div>
    </div>
    <h2 class="mt-4">Mon Compte</h2>
    <div class="list-group">
      <a href="<%= edit_user_registration_path %>" class="list-group-item<%= yield(:tab) == 'profile' ? ' active' : '' %> list-group-item-secondary">Mon
        profil</a>
      <% if current_user.facebook_id.empty? %>
          <a href="<%= user_facebook_omniauth_authorize_path %>" class="list-group-item list-group-item-secondary">Lier
            mon compte à Facebook</a>
      <% end %>
      <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'list-group-item-warning list-group-item' %>
    </div>
    <h2 class="mt-4">Modules</h2>
    <div class="list-group">
      <% if current_user.admin? %>
          <a href="<%= stanhome_products_path %>" class="list-group-item<%= yield(:tab) == 'stanhome' ? ' active' : '' %> list-group-item-secondary">Produits
            StanHome</a>
          <a href="<%= evolutions_path %>" class="list-group-item<%= yield(:tab) == 'evolution' ? ' active' : '' %> list-group-item-secondary">Evolution
            physique</a>
      <% end %>
      <a href="<%= recipes_path %>" class="list-group-item<%= yield(:tab) == 'recipe' ? ' active' : '' %> list-group-item-secondary">Recettes</a>
    </div>
  </div>
</div>